# Gradle Properties
org.gradle.jvmargs=-Xmx3G

# Compilation Options
generate_sources_jar=true
generate_javadocs_jar=false

# Testing
enable_junit_testing=true
show_testing_output=false

# Shadow
enable_shadow=false

# Set this to true if you want to use old LWJGL2 methods.
enable_lwjglx=true

# Mod Information
mod_version=1.0.0
root_package=com.wintercogs.appliedpneumatics
mod_id=appliedpneumatics
mod_name=Applied Pneumatics
mod_license=LGPL-3.0-or-later
mod_description=A PneumaticCraft add-on that integrates with Applied Energistics.
mod_url=https://github.com/FormlessDragon/AppliedPneumatics
mod_update_json=
mod_authors=FormlessDragon
mod_credits=
mod_logo_path=

# Run Configurations
minecraft_username=Developer
extra_jvm_args=
enable_foundation_debug=false

# Maven Publishing
publish_to_maven=false
publish_to_local_maven=false
maven_name=${mod_name}
maven_url=

# Access Transformers
use_access_transformer=false
access_transformer_locations=${mod_id}_at.cfg

# Coremods
is_coremod=false
coremod_includes_mod=false
coremod_plugin_class_name=

# AssetMover
use_asset_mover=false
asset_mover_version=2.5

ae2_version = 1.0.2
pneumaticcraft_version = 2978408